name: kanoon_neka
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7
  lottie: ^1.2.1
  dart_mysql: ^0.0.1
  shamsi_date: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.3
  rflutter_alert: ^2.0.4
  animated_text_kit: ^4.2.1
  flutter_fadein: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/anim/

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iransans_fa.ttf
    - family: IranSansMed
      fonts:
        - asset: assets/fonts/iransans_med_fa.ttf